package com.example.demo.entity;

public class UserAccount {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_account.name
	 * @mbg.generated  Sun Aug 23 20:09:14 JST 2020
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_account.password
	 * @mbg.generated  Sun Aug 23 20:09:14 JST 2020
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_account.role
	 * @mbg.generated  Sun Aug 23 20:09:14 JST 2020
	 */
	private String role;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_account.name
	 * @return  the value of user_account.name
	 * @mbg.generated  Sun Aug 23 20:09:14 JST 2020
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_account.name
	 * @param name  the value for user_account.name
	 * @mbg.generated  Sun Aug 23 20:09:14 JST 2020
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_account.password
	 * @return  the value of user_account.password
	 * @mbg.generated  Sun Aug 23 20:09:14 JST 2020
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_account.password
	 * @param password  the value for user_account.password
	 * @mbg.generated  Sun Aug 23 20:09:14 JST 2020
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_account.role
	 * @return  the value of user_account.role
	 * @mbg.generated  Sun Aug 23 20:09:14 JST 2020
	 */
	public String getRole() {
		return role;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_account.role
	 * @param role  the value for user_account.role
	 * @mbg.generated  Sun Aug 23 20:09:14 JST 2020
	 */
	public void setRole(String role) {
		this.role = role == null ? null : role.trim();
	}
}