package com.example.demo.mapper;

import com.example.demo.entity.MeetingRoom;
import com.example.demo.entity.MeetingRoomExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MeetingRoomMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table meeting_room
	 * @mbg.generated  Sun Aug 23 20:09:14 JST 2020
	 */
	long countByExample(MeetingRoomExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table meeting_room
	 * @mbg.generated  Sun Aug 23 20:09:14 JST 2020
	 */
	int deleteByExample(MeetingRoomExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table meeting_room
	 * @mbg.generated  Sun Aug 23 20:09:14 JST 2020
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table meeting_room
	 * @mbg.generated  Sun Aug 23 20:09:14 JST 2020
	 */
	int insert(MeetingRoom record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table meeting_room
	 * @mbg.generated  Sun Aug 23 20:09:14 JST 2020
	 */
	int insertSelective(MeetingRoom record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table meeting_room
	 * @mbg.generated  Sun Aug 23 20:09:14 JST 2020
	 */
	List<MeetingRoom> selectByExample(MeetingRoomExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table meeting_room
	 * @mbg.generated  Sun Aug 23 20:09:14 JST 2020
	 */
	MeetingRoom selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table meeting_room
	 * @mbg.generated  Sun Aug 23 20:09:14 JST 2020
	 */
	int updateByExampleSelective(@Param("record") MeetingRoom record, @Param("example") MeetingRoomExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table meeting_room
	 * @mbg.generated  Sun Aug 23 20:09:14 JST 2020
	 */
	int updateByExample(@Param("record") MeetingRoom record, @Param("example") MeetingRoomExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table meeting_room
	 * @mbg.generated  Sun Aug 23 20:09:14 JST 2020
	 */
	int updateByPrimaryKeySelective(MeetingRoom record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table meeting_room
	 * @mbg.generated  Sun Aug 23 20:09:14 JST 2020
	 */
	int updateByPrimaryKey(MeetingRoom record);
}