package com.example.demo.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.example.demo.entity.UserAccount;
import com.example.demo.entity.UserAccountExample;


public interface UserAccountMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_account
	 * @mbg.generated  Mon Aug 31 21:21:58 JST 2020
	 */
	long countByExample(UserAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_account
	 * @mbg.generated  Mon Aug 31 21:21:58 JST 2020
	 */
	int deleteByExample(UserAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_account
	 * @mbg.generated  Mon Aug 31 21:21:58 JST 2020
	 */
	int deleteByPrimaryKey(String name);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_account
	 * @mbg.generated  Mon Aug 31 21:21:58 JST 2020
	 */
	int insert(UserAccount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_account
	 * @mbg.generated  Mon Aug 31 21:21:58 JST 2020
	 */
	int insertSelective(UserAccount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_account
	 * @mbg.generated  Mon Aug 31 21:21:58 JST 2020
	 */
	List<UserAccount> selectByExample(UserAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_account
	 * @mbg.generated  Mon Aug 31 21:21:58 JST 2020
	 */
	UserAccount selectByPrimaryKey(String name);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_account
	 * @mbg.generated  Mon Aug 31 21:21:58 JST 2020
	 */
	int updateByExampleSelective(@Param("record") UserAccount record, @Param("example") UserAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_account
	 * @mbg.generated  Mon Aug 31 21:21:58 JST 2020
	 */
	int updateByExample(@Param("record") UserAccount record, @Param("example") UserAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_account
	 * @mbg.generated  Mon Aug 31 21:21:58 JST 2020
	 */
	int updateByPrimaryKeySelective(UserAccount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_account
	 * @mbg.generated  Mon Aug 31 21:21:58 JST 2020
	 */
	int updateByPrimaryKey(UserAccount record);
}